### ISSUE TITLE
Tiling layout half should act like maximized when one window is opened

### ISSUE THREAD

**Issue by nununoisy** [material-shell/material-shell#130]
Title is pretty self explanatory - the wasted half of the screen could be filled this way.

**Comment by codycraven** [comment]
After thinking about this a bit more I think we could have the best of both worlds and allow users to configure the minimum number of windows each layout supports.

For example, say you could define the minimum number of windows for Grid and the user sets the value to 4 (from the default 1). If the user only had one window open on the Grid display the window would take up 1/4 of their screen instead of the full screen.

The same could work with Split, where the user could choose 1 or 2:
- 1 (default) would provide the functionality you're suggesting
- 2 would provide the current functionality

**Comment by nununoisy** [comment]
@codycraven I don't have a screen even close to 40" let alone at 4K, so I probably would have never seen this behavior as useful. But I think that you've found a use-case for this functionality.

I don't think your suggestion would be too difficult to implement and would definitely work for users of all screen sizes.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
