### ISSUE TITLE
Swap panels

### ISSUE THREAD

**Issue by webmastak** [material-shell/material-shell#133]
Add a setting that would swap panels, top panel to left and left panel to top.
[![https://i.imgur.com/qvaDFwV.jpg](https://i.imgur.com/qvaDFwV.jpg)](https://i.imgur.com/qvaDFwV.jpg)

**Comment by codycraven** [comment]
@webmastak how would you suggest applications are displayed? Currently the top panel displays an icon and title for the window which would not work in a vertical display without design changes.

**Comment by webmastak** [comment]
And if you move the top panel to the bottom, left to top and do auto-hide the bottom panel.

**Comment by PapyElGringo** [comment]
The interface must reflect the workflow. Please [read this](https://github.com/PapyElGringo/material-shell/blob/master/documentation/material-shell.md#workflow) to learn more about our workflow. Since the work-spaces are verticals it's logic that the interface related to navigate between them is vertical. It's the same for the windows. It's really un intuitive to swap them.

**Comment by webmastak** [comment]
Thanks for the explanation.

**Comment by PapyElGringo** [comment]
Like explained won't be done at least not for now
