### ISSUE TITLE
Active taskbar text & indicator is not readable on primary theme with white primary color

### ISSUE THREAD

**Issue by anakaiti** [material-shell/material-shell#154]
Output from `git show`:
```
commit beb5c15940626ac6c41aa8579a51761438d2af10
Merge: adb8101 e190db9
Author: PapyElGringo <adrien@pesler.be>
Date:   Thu Dec 5 10:57:19 2019 +0100

    Merge pull request #149 from bbil/layout-ripple
    
    Fix Ripple effect on tiling button


```

![image](https://user-images.githubusercontent.com/5457202/70316143-9df74d80-184d-11ea-8cb4-ba27cde5f2f5.png)

**Comment by nununoisy** [comment]
I'm not sure where the faint green outline is coming from. But that text is intended to be the primary color (i.e. white).

The issue I'm having is that I would have never expected this use case - how would I be able to distinguish the active app from an inactive app? Since there isn't a third color to contrast I'm not sure how to clearly implement that, but it would probably involve patching the Sass.

**Comment by nununoisy** [comment]
As an example, try to identify the active workspace - although it seems straightforward it's not instantly distinguishable because there is not a clear contrast.

**Comment by PapyElGringo** [comment]
Why don't you use the white theme instead? The primary is meant to be a high contrast theme

**Comment by maxerbox** [comment]
Themes will be entirely reworked and this issues is not reproductible anymore.
