### ISSUE TITLE
Make a settings panel

### ISSUE THREAD

**Issue by nununoisy** [material-shell/material-shell#16]
Another thing that has been suggested before is a settings panel. It should be possible to control:
+ Key shortcuts
+ Icons
+ Workspace order/layout/categories
+ etc.

This is accomplished by creating a UI in XML and a prefs JavaScript file. A working implementation can be found in (Dash-to-Dock)[https://github.com/micheleg/dash-to-dock]. Check `prefs.js` and `Settings.ui`.

**Comment by jtebert** [comment]
As part of being able to choose the workspaces in a settings panel, I'd really like to be able to select what applications appear in each panel, rather than by category. (Though that's probably harder to add to the interface given that the current `WorkSpaceEnhacerModule` only has options for including/excluding categories of applications.)

**Comment by nununoisy** [comment]
You might be able to get away with modifying the `.desktop` files somehow to change the category.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
