### ISSUE TITLE
Firefox on Wayland: the first tab is not aligned with the bars

### ISSUE THREAD

**Issue by chris314b** [material-shell/material-shell#191]
Firefox on Wayland: the first tab inside firefox ESR (68.9) is not aligned with the bars (picture). 
Firefox on Xorg is aligned (picture).
On debian testing (bullseye, gnome 3.36.2) with Intel HD Graphic 500 APL 2). 100% reproducible.

![Screenshot-4a-firefox-Wayland](https://user-images.githubusercontent.com/67124994/85198691-ff16d800-b2ea-11ea-96df-24fa2344d134.png)
![Screenshot-4-firefox-xorg](https://user-images.githubusercontent.com/67124994/85198707-1d7cd380-b2eb-11ea-9d32-027b774c5d6a.png)

**Comment by PapyElGringo** [comment]
Probably related to an incompatible extension.

**Comment by chris314b** [comment]
I have disabled all gnome-shell extensions, I have updated the latest version of Material-Shell:
- the problem persists
- since the update, it's now both on Xorg and Wayland.

**Comment by xd003** [comment]
i am facing this issue in latest material shell version with firefox on Xorg as well
OS - Arch Linux ( x86_64 )
Firefox - v80.0.1
gnome-shell-extension-material-shell-git r604.688ce24-1

**Comment by cshei** [comment]
I think this is because Firefox detects when it's snapped to half the screen and does something special to eliminate the blank space.  Without Material Shell enabled, unsnapped and unminimized Firefox looks exactly like it does in Material Shell.  But snapping or maximizing Firefox causes the blank space to go away in regular GNOME, whereas in MS it does not.

I have no idea how this is detected/done, but perhaps it would be possible for Material Shell to also trigger this maximized/snapped behavior as appropriate?
