### ISSUE TITLE
[Feature Request] - Pin window to workspace

### ISSUE THREAD

**Issue by dioio-io** [material-shell/material-shell#232]
As a user, I would like for when I persist a window on an workspace, it renders me unable to move the window across workspaces, or at least add another option to persist on specific workspace as well

**Comment by PapyElGringo** [comment]
Could be related to https://github.com/material-shell/material-shell/issues/217 But I have some trouble to understand the need for both request since there isn't any automatic window displacement anymore. Moving a window should now be purely human interaction so if you don't move it it's shouldn't move. Except if you have a kind of Parkison disorder ?

**Comment by dioio-io** [comment]
Well, sometimes I accidentally move window to another workspace, and then i get lost since i have planned what window is pinned in what workspace, so i would accidentally move, lets say the the code window to whereever my music app is, and then going back to the code workspace, it wouldnt be there!
This would allow for a way to persist the planned workflow and workspace a bit more :)

**Comment by PapyElGringo** [comment]
I'm curious on how you accidentally move a window then

**Comment by dioio-io** [comment]
I suppose it just happens, and quite frequently to be honest!

How about adding this option:
```xml
    <key name="disable-workspace-moving-on-persisted-windows" type="b">
      <default>false</default>
      <summary>Disable workspace moving on persisted windows</summary>
      <description>If a window is persisted, disallow user to move window to another workspace</description>
    </key>
```

**Comment by PapyElGringo** [comment]
I'm not against adding a setting but I would prefer to dig up a bit the issue. Ideally I would prefer prevent accident window displacement.
How do you move windows accross workspaces? Is that because you are trying to navigate throught keyboard shortcut and with the lack of habit you use the wrongs ones?

**Comment by dioio-io** [comment]
Ill try to to gather user feedback first and if theres insufficient interest i will close the issue
