### ISSUE TITLE
Gnome terminal - not fully maximized.

### ISSUE THREAD

**Issue by krishnaraj** [material-shell/material-shell#327]
The gnome terminal is not fully maximized and there is always a small gap at the bottom.

![image](https://user-images.githubusercontent.com/141018/94117281-a9ae1200-fe69-11ea-9c11-23aa01646dba.png)

**Comment by Chrysostomus** [comment]
Dublicate of #166? 

https://github.com/material-shell/material-shell/issues/166

But this happens with only one window... 🤔 Is material shell just resizing singlw windows to full size instead of maximizing the window? I think we would get the best experience by

- maximizing lone windows
- using side splits for 2 windows

After 2 windows gaps can't be helped because of the limitations of mutter

**Comment by krishnaraj** [comment]
Yes, this is indeed a duplicate of #166 . Sorry for not looking properly :)

**Comment by PapyElGringo** [comment]
@Chrysostomus It was the plan but there was some crash when jumping from `maximize` to `minimize`
I'll need to recheck
