### ISSUE TITLE
Black screen with dual monitor ubuntu 20.04

### ISSUE THREAD

**Issue by pedrosousagrilo** [material-shell/material-shell#534]
**Describe the bug**
Hello,
First thing, I would like to say that I really like Material shell (specially with the resize feature).
I made the update from gnome extensions and got black screen on both monitors every time I connected a second monitor. Spent all morning trying to figure it out what was happening and only after disabling material shell I realize it was the problem.

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04

**Comment by pedrosousagrilo** [comment]
https://github.com/material-shell/material-shell/issues/537

**Comment by dziurka** [comment]
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.38.2
- Distro: Solus Gnome

After the last system updates (solus is a rolling release distribution) the material shell freezes my entire gnome environment. I am not even able to restart the shell (alt + f2, r), only the mouse cursor works. I even restarted all material-shell settings with dconf, but that didn't help.
The problem appears only with the connected second monitor - no matter if it is connected before logging in or after.

The problem is certainly with material-shell, as I even uninstalled other add-ons, and the gnome with material-shell disabled works fine.
