### ISSUE TITLE
Its Glitchy, because i always when i click anything it clicks something else 

### ISSUE THREAD

**Issue by yoge67855** [material-shell/material-shell#574]
its like that:
When i click to disable extension opens settings or other thins

**Comment by yoge67855** [comment]
and one more question is: how to reset it do default settings

**Comment by ikelos** [comment]
To add a little more description to this, I've found occasions where clicks appear to click on the window as if it were at the absolute top left corner of the screen, rather than having the top and side bar (so to click on a button you must click above and to the left).  I found that this persisted even after restarting the shell until I eventually had to delete `~/.local/share/gnome-shell/material-shell-state`.  This might be what was briefly described above.
