### ISSUE TITLE
updateMetaWindowPositionAndSize questions

### ISSUE THREAD

**Issue by xendk** [material-shell/material-shell#643]
This is neither a feature request nor a bug, but some questions.

When digging through `updateMetaWindowPositionAndSize()` and Googling for Gnome docs, I hit this: https://www.reddit.com/r/gnome/comments/kmoeh8/what_exactly_does_the_user_op_paramter_in/ which caught my eye because of the code later in the function that enforces window move if it didn't. Sounds like the exact same thing.

The comments on reddit suggests that Material Shell shouldn't use `true` for user_op on `move_frame`/`move_resize_frame`, and as far as I can tell, the constraints imposed when using `false` shouldn't matter for Material Shell. Is there a specific reason for using `true`?

Secondly, the function seems to expend a lot of energy on figuring out whether to move and resize or only move. Wouldn't it be simpler to just always use `move_resize_frame`? My casual inspection of the logs show `move_resize_frame` being hit just as much as `move_frame` even when just swapping windows (oddly, only one of the pair needs resizing, which doesn't quite make sense), and I would think nobody notices the difference.

Thirdly, it seems to move and resize in an idle callback when running in Wayland, but not in X. I'm guessing something in Wayland needs it to be so, but is there any problem in doing the same in X?

Simplifying the function might not have much practical effect, but it improves maintainability. I could do a PR when I get a bit wiser.

**Comment by PapyElGringo** [comment]
**op parameter:**
The constraint does impact Material Shell because on small screen when using a split layout for exemple and if the second windows minimum width is larger that the available split width, we prefer that the window goes beyond the screen instead of overlapping the first window.

**move_resize_frame VS move_frame:**
Here we starting to dig into the edge cases. At first I started with a single `move_resize_frame` for every call at it works for most of windows but unfortunately it wasn't the case for all windows. In Windows managements there is always some exception and sometimes windows don't behave the same with  `move_frame` and `move_resize_frame`. For some windows just calling `move_resize_frame` create a visual flicker and don't move the window if the size are the same.

**Crashes**
 The complexity of this function is the result of stacking attempt of fixing misbehavior of Mutter or Windows themselves. Since tiling windows with Mutter hasn't been experienced much there is still some edge cases bug that lead to gnome-shell crash. And since we can't patch Mutter directly as an extension we try to mitigate the crashes. The difficulty here is that the crashes depends of the versions of Gnome-shell used and the backends (Wayland or Xorg) And since we tryed to be compatible with multiple gnome-shell version at the same time it's complexify the code. We found that adding some delay on some call help prevent the code exception so we added them only when needed.

In reality this function started by being very simple and go more complex over the time after investigate all the reported bugs.

**Comment by xendk** [comment]
> op parameter
And after I'd posted I started wondering about floating mode and dragging windows. It was just that I noticed that the OP of that reddit thread reported a problem that sounds remarkably like the one you're trying to fix later in the `updateMetaWindowPositionAndSize()` function. If `false` fixes that problem, it might be worth dealing with windows that's too big for their allocated space explicitly.

> we prefer that the window goes beyond the screen instead of overlapping the first window.

But wouldn't that only be the case for the rightmost window in a split? I'd assume if the leftmost is too big, it would still overlap the rightmost, or am I missing something?

> move_resize_frame VS move_frame:
> For some windows just calling move_resize_frame create a visual flicker and don't move the window if the size are the same.

You know of a way to reproduce this? I've tried hacking my local checkout, and so far haven't seen any problems.

> We found that adding some delay on some call help prevent the code exception so we added them only when needed.

Yeah, but would it be a problem doing the same when not in Wayland? If it works just as well in X, is there any reason not to? Less possible different codepaths means less complexity. Also means other code don't have to take into account that `updateMetaWindowPositionAndSize()` might work in different ways.

> In reality this function started by being very simple and go more complex over the time after investigate all the reported bugs.

Oh I know the feeling. It's a rather central and often called function, so I think it's worth trying to re-simplify a bit.

**Comment by PapyElGringo** [comment]
>But wouldn't that only be the case for the rightmost window in a split?

Yes but still important

>You know of a way to reproduce this?

I'm not sure but I think the issue was to swap a gnome-terminal instance in a split layout with another window. The size didn't changed but only the position and some times gnome-terminal didn't moved at all.

>It's a rather central and often called function, so I think it's worth trying to re-simplify a bit.

To get there with an ungly but working function was sooooo painfull I had to understand why crashes occured to only few people and because everyone had different gnome-shell version / apps and use different backend it was a lot of crash and retry. So even if the function is not ideal I know that it's atleast currently working for most of the users which has a great value for me. Simplifying something could just lead to unexpected bugs in some versions

**Comment by xendk** [comment]
> To get there with an ungly but working function was sooooo painfull

Considered "making a break" with a fresh release that only supports the latest Gnome shell version (the upcoming 40 looks like an excellent opportunity)? I know it complicates things to having different versions to support, but it does narrow the window of versions to support in each. I don't know the usage statistics for Gnome, but I would expect the older versions quickly falling out of favor when a new version is released, and the distributions pick up the new.

Having one version and trying to support it on everything leaves you in a sticky situation, as you've pointed out. I've seen people complaining that the Gnome shell API is way too unstable and maintaining an extension across versions is a nightmare. It's difficult to know when some hackery that was necessary for some old version of Gnome/app isn't needed anymor, as nobody's using that version anymore. One can try to remove stuff from one version to the next and see if anyone complains, but that's not going to sit well with users. 

In traditional software development, you usually deal with this kind of cleanup in major releases, but in extensions there's not much more version management than "the latest verision".

So you kinda just accumulate cruft until (that's how it often goes) it grows too nu-managable and you decide to rewrite everything from scratch.

An alternative approach could be to have different versions of subsystems/classes depending on the version of Gnome/X or Wayland/user option. You'd still have the problem of different versions of the same code, but they'd hopefully be simpler (less permutations for each version), and some bugfixes might apply across them.

I'm amazed how you figure out these workarounds across all these different configurations. Do you have virtual machines with different Gnome/X/Wayland?
