### ISSUE TITLE
No Portable Configuration

### ISSUE THREAD

**Issue by Alfredo-Vargas** [material-shell/material-shell#762]
**Dot configuration file for portability no present**
I'm a user that uses Gnome as my desktop environment for my desktop computer, laptop and some virtual machines. Every time I wanna install material-shell I need to manually disable all the default shortcuts of Gnome and adjust my configuration shortcuts of material-shell. I wouldn't mind to this only once. But to do it for every machine that use (physical / virtual) it requires me too much time.

**A simple settings template would be a solution**
A configuration file which I could push to my dotfiles repository would be enough.

**Describe alternatives you've considered**
I'm considering to dig into the configuration files myself and change it accordingly, however I don't know how many files are involved and how to disable all Gnome default shortcuts.

**Comment by Luctins** [comment]
You can use [this](https://extensions.gnome.org/extension/1486/extensions-sync/) for now as it synchronizes extension preferences stored in dconf and material-shell stores all of them (AFAIK) on dconf. 

But having a config file (yaml?) would be nice, since material shell will _eventually_ move away from gnome.

**Comment by Alfredo-Vargas** [comment]
Thank you. I love Material-shell, works out of the box. Cheers.
