### ISSUE TITLE
Update for Gnome 43

### ISSUE THREAD

**Issue by mpolinowski** [material-shell/material-shell#889]
**Is your feature request related to a problem? Please describe.**

Just updated my system and "broke" Material Shell :) Is there an update planned already?

![Screenshot from 2022-09-28 13-52-15](https://user-images.githubusercontent.com/18694428/192699158-6055c317-e212-4507-ab13-b654503fd309.png)

![Screenshot from 2022-09-28 13-50-52-1](https://user-images.githubusercontent.com/18694428/192699185-744b1653-2e32-4925-a766-220976b18176.png)

**Comment by expeehaa** [comment]
The current `main` branch technically supports Gnome 43 since yesterday (see #884), but I’ve found a bug that occurs when hibernating/suspending/locking (not sure which one, didn’t troubleshoot it yet). So while it should be working, it may break at runtime.
I’ll try to fix that in the next days.

Since I’m a fellow Tumbleweed user I’m also interested in getting it done as soon as possible.

**Comment by expeehaa** [comment]
I’ve been using the latest `main` for a few days now, which includes the fix for the issue mentioned above, and haven’t noticed any large issue.
There is some notification code not working (see #890), but it doesn’t break anything for the user, and @PapyElGringo noticed that the search function of the side window that opens when clicking at the search icon in the (by default) top left corner doesn’t work, but that doesn’t bug me.

There hasn’t been a release yet though, and I doubt there will be without at least those 2 issues fixed.
In the meantime, the source install method as described in the README needs to be used (or a system package based on the `main` branch).

**Comment by dilinger** [comment]
Using debian testing with gnome 43 in a virtualbox environment, this crashes immediately for me (with gnome-shell disabling extensions).

**Comment by PapyElGringo** [comment]
All gnome 43 compatibility PRs has been merged so it's should work now

**Comment by mpolinowski** [comment]
The update just arrived - thank you 💯
